import { useEffect } from 'react';
import { useLocation } from 'react-router';
import "./singlepost.css";
import axios from "axios";


export default function Singlepost() {

    const location = useLocation()
    const path = (location.pathname.split("/")[2]);


    useEffect(() => {
        const getPost = async () => {
            const res = await axios.get("/posts/" + path);
            console.log(res)

        };
        getPost()
    }, [path]);

    return (
        <div className="singlepost">
            <div className="singlepostwrapper">
                <img src="" alt=""
                    className="singlepostimg" />
                <h1 className='singleposttitle'>
                    <div className="singlepostedit">
                        <i className="singleposticon far fa-edit"></i>
                        <i className="singleposticon far fa-trash-alt"></i>
                    </div>
                </h1>
                <div className="singlepostinfo">
                    <span className="singlepostauthor">Author: <b> Kirk Smith</b></span>
                    <span className="singlepostdate">14 hr ago</span>
                </div>
                <p className="singlepostdesc"
                >Climate change is defined as shifts in the earth’s climate driven by human activities, mainly greenhouse gas emissions caused by burning fossil fuels. Global temperatures are slated to rise by at least 1.5 degrees Celsius by 2030, but we are already living the devastating impacts of global warming.

                    As the planet warms, extreme weather events such as heatwaves, floods, and droughts become more frequent and intense. Unfortunately, those who have contributed the least to climate change are affected the most. Without immediate action, the climate crisis could lead to widespread poverty, hunger and migration.

                    Africa And the Climate Crisis
                    The African continent will be hit the hardest by climate change, despite contributing only 4% to global carbon emissions. This vulnerability is driven by high levels of poverty across the continent leaving many without the resources to buffer themselves and recover from the changing climate.

                    Global warming, rising sea levels, changing precipitation patterns, and more extreme weather events are already increasing threats to human health, food and water security, and economic development across the continent. Most temperatures across Africa have already risen by 1 degree Celsius.



                    How is SolarAid Helping?
                    Currently, 548 million people in sub-Saharan Africa are without access to electricity. This forces people across the continent to cut their day short at around 6pm, with many relying on expensive, toxic, and harmful lighting sources such as candles and kerosene lamps. In turn, these alternatives are damaging the environment. One kerosene lamp emits 370kg of carbon dioxide emissions into the atmosphere every single year.

                    This unacceptable situation has a negative impact on every facet of life, trapping people in poverty and leaving them even more vulnerable to climate change.

                    The answer? Solar lights.

                    Small solar lights have a big impact. With each solar light decreasing CO2 emissions by 1.1 tonnes, not only do they represent the first step on the road to a cleaner, safer, renewable future, but our research also shows that this first step has a greater impact than any subsequent step ‘up the energy ladder.’ For the first time, families can stop using dangerous, polluting kerosene lamps and candles. This means more study hours, greater economic opportunity and better overall health.

                    "There are no magic bullets that will solve all of our greenhouse gas problems, but replacing kerosene lamps is a low-hanging fruit."
                    Earth is surrounded by an immense magnetic field, called the magnetosphere. Generated by powerful, dynamic forces at the center of our world, our magnetosphere shields us from erosion of our atmosphere by the solar wind, particle radiation from coronal mass ejections (eruptions of large clouds of energetic, magnetized plasma from the Sun’s corona into space), and from cosmic rays from deep space. Our magnetosphere plays the role of gatekeeper, repelling these forms of energy that are harmful to life, trapping most of it safely away from Earth’s surface. You can learn more about Earth’s magnetosphere here.

                    Since the forces that generate our magnetic field are constantly changing, the field itself is also in continual flux, its strength waxing and waning over time.
                </p>
            </div>


        </div>
    )
}
